# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
import torch

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
hint(2)

hint: np.__version__, np.show_config)


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10), torch.zeros(10)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### 4. How to find the memory size of any array (★☆☆)

In [30]:
arr = np.zeros(10)
tensor = torch.zeros(10)
np.size(arr), arr.size, arr.itemsize, tensor.size(), tensor.itemsize

(10, 10, 8, torch.Size([10]), 4)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [23]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [34]:
arr[4] = 1
tensor[4] = 1
arr, tensor

(array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]))

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [37]:
np.array(range(10, 49)), torch.tensor(range(10, 49))

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48]),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
         28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
         46, 47, 48]))

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [47]:
arr = np.array(range(1, 10))
tensor = torch.tensor(range(1, 10))
arr[::-1], tensor.flip(dims=[0])

(array([9, 8, 7, 6, 5, 4, 3, 2, 1]), tensor([9, 8, 7, 6, 5, 4, 3, 2, 1]))

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [51]:
np.array(range(0, 9)).reshape(3,3), torch.tensor(range(0, 9)).reshape(3, 3)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [55]:
help(torch.nonzero)

Help on built-in function nonzero in module torch:

nonzero(...)
    nonzero(input, *, out=None, as_tuple=False) -> LongTensor or tuple of LongTensors
    
    .. note::
        :func:`torch.nonzero(..., as_tuple=False) <torch.nonzero>` (default) returns a
        2-D tensor where each row is the index for a nonzero value.
    
        :func:`torch.nonzero(..., as_tuple=True) <torch.nonzero>` returns a tuple of 1-D
        index tensors, allowing for advanced indexing, so ``x[x.nonzero(as_tuple=True)]``
        gives all nonzero values of tensor ``x``. Of the returned tuple, each index tensor
        contains nonzero indices for a certain dimension.
    
        See below for more details on the two behaviors.
    
        When :attr:`input` is on CUDA, :func:`torch.nonzero() <torch.nonzero>` causes
        host-device synchronization.
    
    **When** :attr:`as_tuple` **is** ``False`` **(default)**:
    
    Returns a tensor containing the indices of all non-zero elements of
    :att

In [56]:
np.nonzero([1,2,0,0,4, 0]), torch.nonzero(torch.tensor([1,2,0,0,4, 0])), torch.nonzero(torch.tensor([1,2,0,0,4, 0]), as_tuple=True)

((array([0, 1, 4]),),
 tensor([[0],
         [1],
         [4]]),
 (tensor([0, 1, 4]),))

#### 11. Create a 3x3 identity matrix (★☆☆)

In [61]:
np.eye(3,3), torch.eye(3,3)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [69]:
np.random.rand(3,3,3), torch.rand(3,3,3)

(array([[[0.48049626, 0.52646723, 0.42023805],
         [0.53690357, 0.37042602, 0.00222212],
         [0.73048973, 0.04514604, 0.38353187]],
 
        [[0.93450665, 0.7569837 , 0.58048241],
         [0.77281926, 0.1873846 , 0.39333366],
         [0.42655546, 0.12807381, 0.65540159]],
 
        [[0.03755073, 0.07980621, 0.70134846],
         [0.35645586, 0.22521772, 0.93383246],
         [0.80230872, 0.91190253, 0.88470506]]]),
 tensor([[[0.7305, 0.9478, 0.8715],
          [0.7458, 0.6189, 0.6983],
          [0.2002, 0.3125, 0.5433]],
 
         [[0.6660, 0.8687, 0.3550],
          [0.0937, 0.0051, 0.9644],
          [0.2285, 0.1205, 0.6348]],
 
         [[0.7629, 0.6230, 0.6946],
          [0.3515, 0.4702, 0.3530],
          [0.3024, 0.5493, 0.9507]]]))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [71]:
arr = np.random.rand(10, 10)
tensor = torch.rand(10, 10)
np.max(arr), np.min(arr), torch.max(tensor), torch.min(tensor)

(np.float64(0.9936978397439458),
 np.float64(0.0008811584570268538),
 tensor(0.9983),
 tensor(0.0015))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [74]:
np.random.rand(30).mean(), torch.rand(30).mean()

(np.float64(0.4346793051568015), tensor(0.4801))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [103]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0

tensor = torch.ones((5,5))
tensor[1:-1, 1:-1] = 0
arr, tensor

(array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 0., 0., 0., 1.],
         [1., 0., 0., 0., 1.],
         [1., 0., 0., 0., 1.],
         [1., 1., 1., 1., 1.]]))

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [92]:
help(np.zeros_like)

Help on _ArrayFunctionDispatcher in module numpy:

zeros_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None)
    Return an array of zeros with the same shape and type as a given array.
    
    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    
        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    
        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of `a`, otherwise it will be a base-class array. Defaults
        to True.
    shape : int or sequence o

In [107]:
import torch.nn.functional as F

np.pad(arr, pad_width=1, constant_values=3), F.pad(tensor, (1,1,1,1), value=3)

(array([[3., 3., 3., 3., 3., 3., 3.],
        [3., 1., 1., 1., 1., 1., 3.],
        [3., 1., 0., 0., 0., 1., 3.],
        [3., 1., 0., 0., 0., 1., 3.],
        [3., 1., 0., 0., 0., 1., 3.],
        [3., 1., 1., 1., 1., 1., 3.],
        [3., 3., 3., 3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3., 3., 3., 3.],
         [3., 1., 1., 1., 1., 1., 3.],
         [3., 1., 0., 0., 0., 1., 3.],
         [3., 1., 0., 0., 0., 1., 3.],
         [3., 1., 0., 0., 0., 1., 3.],
         [3., 1., 1., 1., 1., 1., 3.],
         [3., 3., 3., 3., 3., 3., 3.]]))

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [80]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [115]:
help(np.diag)

Help on _ArrayFunctionDispatcher in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flatt

In [137]:
np.diag([1,2,3,4], k=-1), torch.diag(torch.tensor([1,2,3, 4]), diagonal=-1)

(array([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]]),
 tensor([[0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 2, 0, 0, 0],
         [0, 0, 3, 0, 0],
         [0, 0, 0, 4, 0]]))

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [150]:
x = np.zeros((8,8))
tensor = torch.zeros((8, 8))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
tensor[::2, 1::2] = 1
tensor[1::2, ::2] = 1
x, tensor

(array([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]]),
 tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
         [1., 0., 1., 0., 1., 0., 1., 0.],
         [0., 1., 0., 1., 0., 1., 0., 1.],
         [1., 0., 1., 0., 1., 0., 1., 0.],
         [0., 1., 0., 1., 0., 1., 0., 1.],
         [1., 0., 1., 0., 1., 0., 1., 0.],
         [0., 1., 0., 1., 0., 1., 0., 1.],
         [1., 0., 1., 0., 1., 0., 1., 0.]]))

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [157]:
help(np.unravel_index)

Help on _ArrayFunctionDispatcher in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    
        .. versionchanged:: 1.16.0
            Renamed from ``dims`` to ``shape``.
    
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``

In [161]:
np.unravel_index(100, (6,7,8)), torch.unravel_index(torch.tensor(100), (6,7,8))

((np.int64(1), np.int64(5), np.int64(4)), (tensor(1), tensor(5), tensor(4)))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain at least one element of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)